version: '3.8'

services:
  books-app:
    image: books-app:latest
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=books_database
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: books_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  admin-panel:
    image: books-app:latest
    command: >
      python -m uvicorn src.wsgi:application --host 0.0.0.0 --port 8001 --interface wsgi --proxy-headers
    ports:
      - "8001:8001"

volumes:
  postgres_data: