version: '3.8'

services:
  books-app:
    image: books-app:latest
    ports:
      - "8000:8000"
    command:
      - python
      - -m
      - books.cli
      # - books-api
    volumes:
      - ./books:/app/books
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=books_database
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: books_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data: