version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: books_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data: